In [210]:
#happy coading

In [211]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [212]:
from pandas_profiling import profile_report

In [213]:
data = pd.read_csv('Parkinsson disease.csv')

In [214]:
data.head()

name  MDVP:Fo(Hz)  MDVP:Fhi(Hz)  ...   spread2        D2       PPE
0  phon_R01_S01_1      119.992       157.302  ...  0.266482  2.301442  0.284654
1  phon_R01_S01_2      122.400       148.650  ...  0.335590  2.486855  0.368674
2  phon_R01_S01_3      116.682       131.111  ...  0.311173  2.342259  0.332634
3  phon_R01_S01_4      116.676       137.871  ...  0.334147  2.405554  0.368975
4  phon_R01_S01_5      116.014       141.781  ...  0.234513  2.332180  0.410335

[5 rows x 24 columns]

In [215]:
data.isna().any()

name                False
MDVP:Fo(Hz)         False
MDVP:Fhi(Hz)        False
MDVP:Flo(Hz)        False
MDVP:Jitter(%)      False
MDVP:Jitter(Abs)    False
MDVP:RAP            False
MDVP:PPQ            False
Jitter:DDP          False
MDVP:Shimmer        False
MDVP:Shimmer(dB)    False
Shimmer:APQ3        False
Shimmer:APQ5        False
MDVP:APQ            False
Shimmer:DDA         False
NHR                 False
HNR                 False
status              False
RPDE                False
DFA                 False
spread1             False
spread2             False
D2                  False
PPE                 False
dtype: bool

In [216]:
dataset = data
y = data['status']
X = data.drop('status',axis=1).iloc[:,2:]

In [217]:
X.head()

MDVP:Fhi(Hz)  MDVP:Flo(Hz)  MDVP:Jitter(%)  ...   spread2        D2       PPE
0       157.302        74.997         0.00784  ...  0.266482  2.301442  0.284654
1       148.650       113.819         0.00968  ...  0.335590  2.486855  0.368674
2       131.111       111.555         0.01050  ...  0.311173  2.342259  0.332634
3       137.871       111.366         0.00997  ...  0.334147  2.405554  0.368975
4       141.781       110.655         0.01284  ...  0.234513  2.332180  0.410335

[5 rows x 21 columns]

In [218]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

# Dimensionality Reduction

In [219]:
 from sklearn.decomposition import PCA
 pca = PCA(n_components=7)
 X = pca.fit_transform(X)

### Total variance covered in the pca

In [220]:
pca.explained_variance_ratio_.sum()

0.947878835378674

In [221]:
pd.DataFrame(X).head()

0         1         2         3         4         5         6
0  2.048121 -1.130448 -1.695405 -0.322770  0.660704  1.184570 -0.533725
1  4.669619 -1.382150 -2.169723  0.834141  1.185343  0.711668  0.104233
2  3.803242 -0.977534 -2.338794 -0.329636  1.161706  0.588434 -0.045230
3  4.085345 -1.338717 -2.145733  0.034313  1.325369  0.612892  0.018515
4  5.642920 -0.582839 -2.890319 -0.306547  0.769975  1.019580 -0.102436

# Model Building

### Logistic Regression

In [222]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score
x_train, x_test, y_train, y_test= train_test_split(X, y, test_size= 0.20, random_state=50)  

In [223]:
from sklearn.linear_model import LogisticRegression  
clf_log = LogisticRegression() 
clf_log.fit(x_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [224]:
logistic_pred = clf_log.predict(x_test)

In [225]:
arr=[]
print(f'Confusion matrix \n {confusion_matrix(y_test,logistic_pred)}')
print('\n \n')
print(f'Accuracy score \n {accuracy_score(y_test,logistic_pred)}')
arr.append(accuracy_score(y_test,logistic_pred))

Confusion matrix 
 [[ 6  5]
 [ 2 26]]

 

Accuracy score 
 0.8205128205128205


### Disicion tree

In [226]:
from sklearn.tree import DecisionTreeClassifier

In [227]:
tree_clf = DecisionTreeClassifier()
tree_clf.fit(x_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [228]:
tree_pred = tree_clf.predict(x_test)
print(f'Confusion matrix \n {confusion_matrix(y_test,tree_pred)}')
print('\n \n')
print(f'Accuracy score \n {accuracy_score(y_test,tree_pred)}')
arr.append(accuracy_score(y_test,tree_pred))

Confusion matrix 
 [[ 6  5]
 [ 2 26]]

 

Accuracy score 
 0.8205128205128205


### Naive bayes

In [229]:
from sklearn.naive_bayes import GaussianNB
naive_clf = GaussianNB()

In [230]:
naive_clf.fit(x_train,y_train)
naive_pred = naive_clf.predict(x_test)

In [231]:
print(f'Confusion matrix \n {confusion_matrix(y_test,naive_pred)}')
print('\n \n')
print(f'Accuracy score \n {accuracy_score(y_test,naive_pred)}')
arr.append(accuracy_score(y_test,naive_pred))

Confusion matrix 
 [[ 6  5]
 [ 4 24]]

 

Accuracy score 
 0.7692307692307693


### Random forest

In [232]:
from sklearn.ensemble import RandomForestClassifier
rand_clf = RandomForestClassifier(max_depth=2, random_state=0)

In [233]:
rand_clf.fit(x_train,y_train)
rand_pred = rand_clf.predict(x_test)

In [234]:
print(f'Confusion matrix \n {confusion_matrix(y_test,rand_pred)}')
print('\n \n')
print(f'Accuracy score \n {accuracy_score(y_test,rand_pred)}')
arr.append(accuracy_score(y_test,rand_pred))

Confusion matrix 
 [[ 5  6]
 [ 0 28]]

 

Accuracy score 
 0.8461538461538461


### Artificial Neural Networks

In [235]:
from tensorflow import keras

In [236]:
model = keras.models.Sequential()

In [237]:
model.add(keras.Input(shape=x_train.shape))
model.add(keras.layers.Dense(20,activation='relu'))
model.add(keras.layers.Dense(20,activation='relu'))
model.add(keras.layers.Dense(1,activation='sigmoid'))

In [238]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_12 (Dense)             (None, 156, 20)           160       
_________________________________________________________________
dense_13 (Dense)             (None, 156, 20)           420       
_________________________________________________________________
dense_14 (Dense)             (None, 156, 1)            21        
Total params: 601
Trainable params: 601
Non-trainable params: 0
_________________________________________________________________


In [239]:
model.compile(optimizer='rmsprop',loss=keras.losses.binary_crossentropy,metrics=['accuracy'])
model.fit(x_train,y_train,epochs=30)

Epoch 1/30
5/5 [==============================] - 1s 3ms/step - loss: 0.7125 - accuracy: 0.5064
Epoch 2/30
5/5 [==============================] - 0s 3ms/step - loss: 0.6532 - accuracy: 0.6410
Epoch 3/30
5/5 [==============================] - 0s 3ms/step - loss: 0.6141 - accuracy: 0.6859
Epoch 4/30
5/5 [==============================] - 0s 3ms/step - loss: 0.5843 - accuracy: 0.7372
Epoch 5/30
5/5 [==============================] - 0s 3ms/step - loss: 0.5584 - accuracy: 0.7756
Epoch 6/30
5/5 [==============================] - 0s 3ms/step - loss: 0.5373 - accuracy: 0.8013
Epoch 7/30
5/5 [==============================] - 0s 4ms/step - loss: 0.5173 - accuracy: 0.8013
Epoch 8/30
5/5 [==============================] - 0s 4ms/step - loss: 0.4991 - accuracy: 0.8333
Epoch 9/30
5/5 [==============================] - 0s 3ms/step - loss: 0.4817 - accuracy: 0.8269
Epoch 10/30
5/5 [==============================] - 0s 3ms/step - loss: 0.4660 - accuracy: 0.8269
Epoch 11/30
5/5 [======================

In [240]:
ann_pred = []
for i in model.predict(x_test):
  if(i>0.5):
    ann_pred.append(1)
  else:
    ann_pred.append(0)

In [241]:
print(f'Confusion matrix \n {confusion_matrix(y_test,ann_pred)}')
print('\n \n')
print(f'Accuracy score \n {accuracy_score(y_test,ann_pred)}')
arr.append(accuracy_score(y_test,ann_pred))

Confusion matrix 
 [[ 6  5]
 [ 1 27]]

 

Accuracy score 
 0.8461538461538461


In [242]:
names = ['Logistic','Decision Tree','Naive Bayes','Random Forest','ANN']
plt.bar(names,arr)
plt.show()

# Hence Random forest and ann gives best accuracy 

### We train random without pca 

In [253]:
y = dataset['status']
X = dataset.drop('status',axis=1).iloc[:,2:]

In [254]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [255]:
x_train, x_test, y_train, y_test= train_test_split(X, y, test_size= 0.20, random_state=50)  

In [256]:
from sklearn.ensemble import RandomForestClassifier
rand_clf = RandomForestClassifier(max_depth=2, random_state=0)
rand_clf.fit(x_train,y_train)
rand_pred = rand_clf.predict(x_test)

In [257]:
print(f'Confusion matrix \n {confusion_matrix(y_test,rand_pred)}')
print('\n \n')
print(f'Accuracy score \n {accuracy_score(y_test,rand_pred)}')

Confusion matrix 
 [[ 5  6]
 [ 3 25]]

 

Accuracy score 
 0.7692307692307693


## **Hence we have prooved model with pca works good comparing to tha model without pca**